-- MySQL Script generated by MySQL Workbench
-- Sun Feb 14 21:43:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_VarejoBoaz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_VarejoBoaz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_VarejoBoaz` DEFAULT CHARACTER SET utf8 ;
USE `db_VarejoBoaz` ;

-- -----------------------------------------------------
-- Table `db_VarejoBoaz`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_VarejoBoaz`.`tb_produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `produto` VARCHAR(45) NOT NULL,
  `preco` DOUBLE NOT NULL,
  PRIMARY KEY (`id_produto`),
  UNIQUE INDEX `id_produto_UNIQUE` (`id_produto` ASC) VISIBLE,
  UNIQUE INDEX `produto_UNIQUE` (`produto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_VarejoBoaz`.`tb_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_VarejoBoaz`.`tb_venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `id_produto` INT NULL,
  `nome_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_tb_venda_tb_produto_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_venda_tb_produto`
    FOREIGN KEY (`id_produto`)
    REFERENCES `db_VarejoBoaz`.`tb_produto` (`id_produto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
