-- MySQL Script generated by MySQL Workbench
-- Mon Feb 15 16:05:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_locadora
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_locadora
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_locadora` DEFAULT CHARACTER SET utf8 ;
USE `bd_locadora` ;

-- -----------------------------------------------------
-- Table `bd_locadora`.`tb_categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_locadora`.`tb_categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_locadora`.`tb_filmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_locadora`.`tb_filmes` (
  `id_filme` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `fk_id_categoria` INT NOT NULL,
  `preco` DOUBLE NOT NULL,
  PRIMARY KEY (`id_filme`, `fk_id_categoria`),
  INDEX `fk_tb_filmes_tb_categorias1_idx` (`fk_id_categoria` ASC) VISIBLE,
  UNIQUE INDEX `id_filme_UNIQUE` (`id_filme` ASC) VISIBLE,
  CONSTRAINT `fk_tb_filmes_tb_categorias1`
    FOREIGN KEY (`fk_id_categoria`)
    REFERENCES `bd_locadora`.`tb_categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_locadora`.`tb_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_locadora`.`tb_clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_locadora`.`tb_aluguel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_locadora`.`tb_aluguel` (
  `fk_id_cliente` INT NOT NULL,
  `fk_id_filme` INT NOT NULL,
  PRIMARY KEY (`fk_id_cliente`, `fk_id_filme`),
  INDEX `fk_tb_clientes_has_tb_filmes_tb_filmes1_idx` (`fk_id_filme` ASC) VISIBLE,
  INDEX `fk_tb_clientes_has_tb_filmes_tb_clientes_idx` (`fk_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_clientes_has_tb_filmes_tb_clientes`
    FOREIGN KEY (`fk_id_cliente`)
    REFERENCES `bd_locadora`.`tb_clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_clientes_has_tb_filmes_tb_filmes1`
    FOREIGN KEY (`fk_id_filme`)
    REFERENCES `bd_locadora`.`tb_filmes` (`id_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
